### ISSUE TITLE
Remove user ids

### ISSUE THREAD

**Issue by YaManicKill** [YaManicKill/flairhq#356]
I'm done. We need to get rid of the user id. It shouldn't exist.

List of what needs to be done:

1. Change all calls to users to use name rather than id  
2. Change creation of users  
3. Create script to remove ids, and change all references/games/etc to use username
4. Test script works

And during deployment:

1. Take down fapp  
2. Backup, move offsite
2. Deploy new code  
3. Run script  
4. Ensure script ran successfully
5. Bring fapp back up

**Comment by not-an-aardvark** [comment]
The script should do the following:

1. Run a query to get every `user`, and store a map of `userid` --> `username`.
2. For every `user`, change the `_id` field from `ObjectId("some_userid")` to `ObjectId("the_corresponding_username")`.
3. For every `comment`, change the `user` field from `"some_userid"` to `"the_corresponding_username"`.
4. For every `game`, change the `user` field from `"some_userid"` to `"the_corresponding_username"`.
5. For every `reference`, change the `user` field from `"some_userid"` to `"the_corresponding_username"`.
6. For every `modnote`, change the `refUser` field from `"some_userid"` to `"the_corresponding_username"`.
7. It's probably easiest just to delete all the `sessions`, so do that.

A few things to consider:
* What should we do if there are two different `userid`s for a given `username`? We could map both of those `userid`s to that `username` during step 1, but that could result in duplicate entries, because references will appear for a user that didn't appear before. It might be better to only map the first `userid` so that the userspace doesn't change.
* What should we do if there's a `comment`, `game`, `reference`, or `modnote` which has a ghost `userid` (i.e. a `userid` that doesn't exist) for whatever reason? I think it would be best to just delete those, since they don't do anything except take up database space.

**Comment by not-an-aardvark** [comment]
[I made the script](https://gist.github.com/not-an-aardvark/7473682691b33ae879e1). It seems to work on my somewhat-small sample database, though we should probably test it on something larger.

**Comment by YaManicKill** [comment]
Ach python. Euch.
