### ISSUE TITLE
Modmail search

### ISSUE THREAD

**Issue by YaManicKill** [YaManicKill/flairhq#395]
This will involve a few parts

1. Archiving modmail on a regular basis (I'm not sure about storage of this, but I don't think it would be too bad), we get a limit of 15000 at a time, so we want to build up a history of the modmail
2. Searching through the archive of modmail and showing results from that
3. Searching through the old archive.txt files, and showing a link to them if we see any result in it (this means that mods don't need to click on it to find out there is no result in it, and it also means we don't have to bother parsing everything in that file as it is a horrible, horrible format).

**Comment by not-an-aardvark** [comment]
We may also want to have the modmail files themselves downloadable by mods, that way we can stop using the other link.

**Comment by YaManicKill** [comment]
I think you misunderstand how it's going to work.

If there isn't anything we can find from what we got from the Reddit API,it will just search through the archived file and show a link to it for the mod to open. 

Does that make sense?

**Comment by not-an-aardvark** [comment]
Yes, I think so. In addition to the feature you mentioned, I was thinking we could also make the files themselves available for download (by mods only, of course). That way we could stop hosting them on Dropbox, which might be a good idea because it would be bad if the links to the files got accidentally leaked or something.

For the first feature (modmail search), it might be good to make a new Model for modmails, and then store them in the database instead of on a file. That way we wouldn't have to deal with the formatting, and we could easily have it auto-refresh whenever someone does a search.

**Comment by YaManicKill** [comment]
> For the first feature (modmail search), it might be good to make a new Model for modmails, and then store them in the database instead of in the file.

Yes, that's absolutely what I was planning. The file is just for things we can't get from the reddit API.

> In addition to the feature you mentioned, I was thinking we could also make the files themselves available for download (by mods only, of course).

That's exactly what I meant. I'm not sure what you thought I meant.
